name: Node.js CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Controller tests
      run: npm run test-controller

    - name: Start API
      run: npm start &

    - name: Wait for API Execution
      run: sleep 5

    - name: Run API tests via HTTP
      run: npm run test-external